class Constants{
  static const List<String> choices = <String>[
    "Edit",
    "Delete",
  ];

  static const List<String> complaintCategory = [
    "Trash Disposal",
    "Sewage Problems",
    "Traffic",
    "Water clogging",
    "Damaged Roads",
    "Street Lights",
    "Electricity",
    "Drainage Problem",
    "Add Category"
  ];

  static const List<String> postCategory = [
    "Greenery",
    "Clean Road",
    "RCC Road",
    "Trashing Facility",
    "Add Category"
  ];

  static const List<String> areas= [
    "Gotri",
    "Bhayli Road",
    "Tarsali",
    "Gorwa",
    "Waghodia",
    "Vasna",
    "Vasna Road",
    "Padra Road",
    "Akota Road",
    "Sama-Savil Road",
    "Ellora Park",
    "VIP Road",
    "Productivity Road",
    "Alkapuri",
    "Siddharth Nagar",
    "Maneja",
    "Harni Road",
    "Kalali",
    "Sevasi",
    "Race Course",
    "Sun Pharma Road",
    "Ajwa Road",
    "Dabhoi Road",
    "Nizampura",
    "Manjalpur",
    "Karelibaug",
    "Pratapgunj",
    "Fatehgunj",
    "Akota",
    "Gotri Road",
    "Subhanpura",
    "Mandvi",
    "Makarpura",
    "Airport Harni Main Road",
    "Chhani Jakat Naka",
    "Vasna-Bhayli Road",
    "Waghodia Road",
    "Ranoli",
    "Sama",
    "Dashrath",
    "Bil-Chapad Road",
    "Jambuva",
    "Vadsar",
    "Harni",
    "Atladara",
    "Chhani",
    "New Sama Bhadran Nagar",
    "Parda Road",
    "Sayaji Park Society",
    "Kendranagar",
    "Chipad",
    "Halol",
    "Sayajigunj",
    "Kalali Road",
    "Karadiya",
    "Bajwa",
    "Laxmipura",
    "New VIP Road",
    "Mahapura",
    "Bill Road",
    "Nani Bapod",
    "Jaspur",
    "Vemali",
    "Vadodara-Anklav Road",
    "Nandesari",
    "Asoj",
    "Sokhda",
    "Ravaliya Mahudevegon",
    "Manjusar",
    "Tandalja",
    "Khanpur",
    "New Sama",
    "Undera",
    "koyali",
    "Padra",
    "Mujar Gamdi",
    "Bhayli",
    "Umeta",
    "Ramwadi",
    "Talsat",
    "Sherkhi",
    "New Karelibaug",
    "Suryanagar",
    "Darshali",
    "Jambubet",
    "Bapunagar",
    "Vadodara-Halol Highway",
    "Bakrawadi",
    "Wadi",
    "Warasiya",
    "Vishwamitri",
    "Shukla Nagar",
    "Saiyed Vasna",
    "Nagarwada",
    "Moghul Wada",
    "Diwalipura",
    "New Alkapuri",
    "Rasulabad",
    "Shiyabaug",
    "Sangma",
    "Jetalpur road",
    "New Sama road",
    "Harinagar",
    "Samta",
    "Karjan",
    "Vijay Nagar",
    "Kapurai Village",
    "Chokshi Bazar",
    "Panchvati",
    "Kevdabaug",
    "Soma Talav",
    "Dabhoi",
    "Dandia Bazar",
    "Dumad",
    "Raopura",
    "Pratham Upvan",
    "Madhavpura",
    "Muj Mahuda",
    "Danteshwar",
    "Somnath Nagar",
    "Sankarda",
    "Haripura",
    "Jarod",
    "Navapura",
    "Lalbaug",
    "Kishanwadi",
    "Kodarvaya",
    "Ratanpur",
    "Sankhyad",
    "Khatamba",
    "Old Padra Road",
    "Puniyad",
    "Sultanpura",
    "Alamgir",
    "Vadiwadi",
    "Atladra Padra Road",
    "Fatehpura",
    "Waghodia-Dabhoi Ring Road",
    "Bill-Chansad Road",
    "Jetalpur",
    "Limdi",
    "Jeasnpura",
  ];
}
